In [10]:
import pandas as pd
kospi_2019 = pd.read_excel('./excel/2019년 코스피.xlsx')
kospi_2019.head()

,일자,종가,대비,등락률,시가,고가,저가,거래량,거래대금,상장시가총액,외국인 합계,Unnamed: 11,Unnamed: 12
0,2019/12/30,2197.67,-6.54,-0.30,2202.62,2208.04,2195.65,416403,4113598,1475909366,16868,NaN,NaN
1,2019/12/27,2204.21,6.28,0.29,2183.70,2215.55,2177.40,490168,5429665,1480287931,28745,NaN,NaN
2,2019/12/26,2197.93,7.85,0.36,2192.22,2198.01,2183.90,571309,4795110,1477949501,40467,NaN,NaN
3,2019/12/24,2190.08,-13.63,-0.62,2206.23,2206.23,2187.58,569968,4756455,1472110435,-10069,NaN,NaN
4,2019/12/23,2203.71,-0.47,-0.02,2208.22,2209.20,2196.43,502034,4734276,1480981911,-19672,NaN,NaN

In [11]:
kospi_2019

,일자,종가,대비,등락률,시가,고가,저가,거래량,거래대금,상장시가총액,외국인 합계,Unnamed: 11,Unnamed: 12
0,2019/12/30,2197.67,-6.54,-0.30,2202.62,2208.04,2195.65,416403,4113598,1475909366,16868,NaN,NaN
1,2019/12/27,2204.21,6.28,0.29,2183.70,2215.55,2177.40,490168,5429665,1480287931,28745,NaN,NaN
2,2019/12/26,2197.93,7.85,0.36,2192.22,2198.01,2183.90,571309,4795110,1477949501,40467,NaN,NaN
3,2019/12/24,2190.08,-13.63,-0.62,2206.23,2206.23,2187.58,569968,4756455,1472110435,-10069,NaN,NaN
4,2019/12/23,2203.71,-0.47,-0.02,2208.22,2209.20,2196.43,502034,4734276,1480981911,-19672,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,2019/01/08,2025.27,-11.83,-0.58,2038.68,2042.70,2023.59,397831,4826642,1333996221,-7687,NaN,NaN
242,2019/01/07,2037.10,26.85,1.34,2034.24,2048.06,2030.90,440191,5301385,1342381871,18529,NaN,NaN
243,2019/01/04,2010.25,16.55,0.83,1992.40,2011.56,1984.53,408991,5490148,1323719373,-1900,NaN,NaN
244,2019/01/03,1993.70,-16.30,-0.81,2011.81,2014.72,1991.65,427976,5358519,1312758913,-6778,NaN,NaN
245,2019/01/02,2010.00,-31.04,-1.52,2050.55,2053.45,2004.27,326368,4295872,1323645397,-7944,NaN,NaN

In [ ]:
import os

path = "./csv/2019_kospi200/"

file_list = []

for filename in os.listdir(path):
    if filename.endswith('.csv'):
        file_list.append(filename)

file_list.sort()
full_df = pd.DataFrame()

for file in file_list:
    temp_df = pd.read_csv(path+file, encoding='CP949')
#     temp_df = temp_df.drop(['종목코드', '종가', '대비', '상장주식수'], axis=1)
    temp_df = temp_df[temp_df['종목명']=='SK텔레콤']
    full_df = pd.concat([full_df, temp_df])
    full_df.reset_index(drop=True, inplace=True)
full_df.to_csv('./csv/2019_SK텔레콤.csv', encoding='CP949')

In [9]:
kospi_list = pd.read_csv('./csv/kospi200_20200102.csv', encoding='CP949')
kospi_list.head()

FileNotFoundError: [Errno 2] No such file or directory: './csv/kospi200_20200102.csv'

In [73]:
kospi_list["종목명"] = kospi_list["종목명"].astype(str)

In [87]:
kospi200_name = pd.DataFrame()
kospi200_name["종목명"] = ""

kospi200_name["종목명"] = kospi_list["종목명"]
kospi200_name

          종목명
0        삼성전자
1      SK하이닉스
2        셀트리온
3    삼성바이오로직스
4         현대차
..        ...
196       SBS
197    S&T모티브
198        무학
199       팜스코
200     한진중공업

[201 rows x 1 columns]

In [88]:
data_1314 = pd.read_csv("./csv/data_1314_20220709.csv", encoding="CP949")
data_1314

,종목코드,종목명,종가,대비,등락률,상장주식수,외국인 보유수량,외국인 지분율,외국인 한도수량,외국인 한도소진율
0,095570,AJ네트웍스,4530,25,0.55,46822295,3743075,7.99,46822295,7.99
1,068400,AJ렌터카,12350,50,0.41,22146300,1202974,5.43,22146300,5.43
2,006840,AK홀딩스,51900,-2100,-3.89,13247561,2009793,15.17,13247561,15.17
3,027410,BGF,7960,-110,-1.36,95369179,10470393,10.98,95369179,10.98
4,282330,BGF리테일,205500,1500,0.74,17283906,5927959,34.30,17283906,34.30
...,...,...,...,...,...,...,...,...,...,...
896,069260,휴켐스,23400,-700,-2.90,40878588,6276588,15.35,40878588,15.35
897,000540,흥국화재,4795,90,1.91,64242645,1348049,2.10,64242645,2.10
898,000547,흥국화재2우B,24250,-450,-1.82,153600,977,0.64,153600,0.64
899,000545,흥국화재우,5010,-240,-4.57,768000,4032,0.53,768000,0.53
900,003280,흥아해운,404,2,0.50,175643430,48009214,27.33,175643430,27.33

In [86]:
kospi200_merge = pd.merge(kospi200_name, data_1314, how='inner')
kospi200_merge

,종목명,종목코드,종가,대비,등락률,상장주식수,외국인 보유수량,외국인 지분율,외국인 한도수량,외국인 한도소진율
0,삼성전자,005930,38750,50,0.13,5969782550,3318291327,55.58,5969782550,55.58
1,SK하이닉스,000660,60600,100,0.17,728002365,352111920,48.37,728002365,48.37
2,셀트리온,068270,214500,-8000,-3.60,125456133,24631705,19.63,125456133,19.63
3,삼성바이오로직스,207940,374000,-12500,-3.23,66165000,5709584,8.63,66165000,8.63
4,현대차,005380,114000,-4500,-3.80,213668187,97931727,45.83,213668187,45.83
...,...,...,...,...,...,...,...,...,...,...
196,SBS,034120,21100,1100,5.50,18252582,0,0.00,0,0.00
197,S&T모티브,064960,27400,350,1.29,14623136,2581713,17.65,14623136,17.65
198,무학,033920,13550,-50,-0.37,28500000,5829647,20.45,28500000,20.45
199,팜스코,036580,7530,-250,-3.21,36727943,2262212,6.16,36727943,6.16
200,한진중공업,097230,1590,-65,-3.93,106052508,6055639,5.71,106052508,5.71